-- Create the tasks table
create table public.tasks (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  title text not null,
  type text not null check (type in ('feature', 'sr')),
  start_date date not null,
  end_date date not null,
  member_id int not null -- Keeping member_id simple for now (1-5)
);

-- Enable Row Level Security (RLS)
alter table public.tasks enable row level security;

-- Create a policy that allows anyone to do anything (since this is a simple internal tool)
-- WARN: In a real public app, you would restrict this!
create policy "Allow all operations for anon users"
on public.tasks
for all
using (true)
with check (true);
